# Generated by Django 4.0.5 on 2022-07-26 02:36

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_archivedocument_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('material', models.CharField(choices=[('mineral', 'Mineral or Hydrocarbon'), ('bone', 'Bone or Ivory'), ('glass', 'Glass'), ('ceramic', 'Ceramic')], max_length=20)),
                ('model3d', models.URLField(max_length=400)),
                ('photo_image', stdimage.models.StdImageField(force_min_size=False, upload_to='photographs', variations={'thumbnail': {'height': 300, 'width': 300}})),
            ],
        ),
    ]
