# Generated by Django 2.2.26 on 2022-08-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20220808_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='material',
            field=models.CharField(choices=[('other', 'Other'), ('plastic', 'Plastic'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('metal', 'Metal'), ('bamboo', 'Bamboo'), ('wood', 'Wood'), ('porcelain', 'Porcelain')], default='glass', max_length=50),
        ),
    ]
